### ISSUE TITLE
document pacapt -U in help

### ISSUE THREAD

**Issue by anntzer** [icy/pacapt#104]
`pacapt --help` does not include an entry indicating that `pacapt -U` (e.g. `pacapt -U localpath`) is supported.

**Comment by icy** [comment]
@anntzer Thanks for your reporting . 

Would you mind sending a PR? The contents are here https://github.com/icy/pacapt/blob/ng/lib/help.txt.

**Comment by anntzer** [comment]
Nah, you get to do it 😃 (feel free to close the issue if got don't plan to).

**Comment by icy** [comment]
@anntzer The best way is to look at the table (https://github.com/icy/pacapt#implemented-operations), or to use `-P` to list all supported options on your distribution. I like to have a better `--help` page, but I haven't had any good idea.
