### ISSUE TITLE
pacapt --version

### ISSUE THREAD

**Issue by anntzer** [icy/pacapt#105]
Fairly trivial note: `pacapt` only supports `-V` for printing the version, whereas `pacman` supports both `-V` and `--version`.

**Comment by icy** [comment]
Hi @anntzer , the `-V` option prints the `pacapt` version, and `-v` and `--version` have something to do with the system package manager. `pacapt` scripts use several uppercase options for its purpose, e.g.

* `-V`: print `pacapt` version
* `-P`: print a list of supported operations

Do you want to have something like `pacapt --Version`? 

Btw, I have found that it's a little hard to pass the `-v` or `--version` to the system packager correctly. For example on `Debian` systems,

```
$ pacapt -- --version
Usage: pacapt <options>   # -h for help, -P list supported functions
```

I'm not sure if this would be a problem, as the script always expects some major operations (install, update, etc.)

**Comment by anntzer** [comment]
Oh, I missed the fact that there's both the version of pacapt and the version of the wrappee.
I guess a possibility would be to have `--version`/`-V`/whatever flag you decide print e.g.
```
pacapt version ...
(etc.)

Currently wrapping:

apt version ...
(etc.)
```
Anyways, not a big deal.

**Comment by icy** [comment]
In new implementation of `pacapt` in `Dlang` (https://github.com/icy/pacapt/tree/nd), we have `pass through` mode which can help to detect the version of the back-ends. For examples,

```
$ pacapt -V # print pacapt version
$ pacapt --version # Without any capital options, passthrough is enabled, `--version` is sent directly to backend
$ pacapt -- -V # pacapt is invoked without any argument; -V is sent to the back-end.
```
