### ISSUE TITLE
Support Void Linux

### ISSUE THREAD

**Issue by BurhanDanger** [icy/pacapt#116]

**Comment by SsNiPeR1** [comment]
whats wrong with void linux?
there is no package manager?

**Comment by icy** [comment]
Hi @BurhanDanger and @SsNiPeR1 , 

We have a PR here https://github.com/icy/pacapt/pull/99 but it's not updated/merged yet.

**Comment by TabulateJarl8** [comment]
I added support in #215, although #200 may be another option, not sure which is better to be merged

**Comment by icy** [comment]
Released in https://github.com/icy/pacapt/issues/116
