### ISSUE TITLE
-Rs support on homebrew

### ISSUE THREAD

**Issue by Mnkai** [icy/pacapt#123]
To the developers of pacapt:

Hello,

First, thank you for making such a nice wrapper, it made my migration from the Arch Linux system to the MacOS system whole lot easier.

While I was tidying my system, I found out `-Rs` option is not supported, despite documentation says it is supported.

<img width="762" alt="image" src="https://user-images.githubusercontent.com/10909652/53060126-aec41600-34fc-11e9-86d2-7a6c2fcbf6fc.png">

Since homebrew itself does not provide removing orphaned packages while removing packages (tapping [rmtree](https://github.com/beeftornado/homebrew-rmtree) does add support, but it's a whole other issue), I guess it might be possible to be a documentation error rather than parameter parsing bug, but just to make sure I've made this issue.

Again, thank you for helping me.

Sincerely,
Minori Hiraoka

**Comment by Mnkai** [comment]
*P.S. Version of installed pacapt is 2.4.0, precompiled from homebrew.

<img width="762" alt="image" src="https://user-images.githubusercontent.com/10909652/53060526-32323700-34fe-11e9-9d02-a6d47d177af1.png">

**Comment by icy** [comment]
Thanks for your report @Mnkai . I don't have Mac to test and I would need some helps from other developers.

@xiongchiamiov  Do you have any ideas?

**Comment by Mnkai** [comment]
I made a pull request #124 which solves this problem.

**Comment by Mnkai** [comment]
Since PR #124 is merged, I will now close this issue.

**Comment by icy** [comment]
Sorry for this belated feedback. I'd like to thank you a lot for your report and your contributing @Mnkai .
