### ISSUE TITLE
Error/delayed/no autocomplete on xubuntu 20.04

### ISSUE THREAD

**Issue by itsTyrion** [icy/pacapt#132]
Using bash, zsh or fish, I can tabcomplete sudo apt install <beginOfPackageName> just fine. 
Using sudo pacman -S, tabcomplete doesn't work on bash or zsh. On fish it works but pretty delayed + it gives an error: 
![image](https://user-images.githubusercontent.com/17730120/83541448-f4420200-a4f9-11ea-8f0b-d6f9313f402f.png)

**Comment by icy** [comment]
hi @itsTyrion , it's also discussed in this https://github.com/icy/pacapt/issues/79. I haven't used any kind of autocompletion so I would expect someone to have Pr. 

@cuonglm can you please help? 

Thanks

**Comment by cuonglm** [comment]
> hi @itsTyrion , it's also discussed in this #79. I haven't used any kind of autocompletion so I would expect someone to have Pr.
> 
> @cuonglm can you please help?
> 
> Thanks

I don't have Linux now, but you can always do:

```
complete -p pacman
```

And use the same output of above command, but replace pacmac by pacapt.

**Comment by icy** [comment]
This problem should be fixed by  https://github.com/icy/pacapt/issues/79 .
