### ISSUE TITLE
Qo should check PATH if arg not found as relative or absolute path

### ISSUE THREAD

**Issue by AndydeCleyre** [icy/pacapt#141]
```console
$ mkdir empty
$ cd empty
```

Arch, real `pacman`:

```console
$ pacman -Qo ls
/usr/bin/ls is owned by coreutils 8.32-1
$ touch ls
$ pacman -Qo ls
error: No package owns ls
```

Alpine:

```console
$ pacapt -Qo ls
ERROR: ls: Could not find owner package
$ touch ls
$ pacapt -Qo ls
ERROR: /empty/ls: Could not find owner package
```

Fedora:

```console
$ pacapt -Qo ls
error: file /home/dev/empty/ls: No such file or directory
$ touch ls
$ pacapt -Qo ls
file /home/dev/empty/ls is not owned by any package
```

**Comment by icy** [comment]
@AndydeCleyre I also like to have this feature, however supporting it is not so easy. It's more about the things that the upstream package manager (yum, apk) would do:

https://github.com/icy/pacapt/blob/0ef1133fc34a34a0099514106f4a9cb6019732fc/lib/apk.sh#L38

@cuonglm Any idea?

**Comment by cuonglm** [comment]
> @AndydeCleyre I also like to have this feature, however supporting it is not so easy. It's more about the things that the upstream package manager (yum, apk) would do:
> 
> 
> 
> https://github.com/icy/pacapt/blob/0ef1133fc34a34a0099514106f4a9cb6019732fc/lib/apk.sh#L38
> 
> 
> 
> @cuonglm Any idea?

II don’t think we should add this, it adds more complexity without any much benefit.

**Comment by AndydeCleyre** [comment]
OK. Just to flesh out how I stumble over this:

I use `-Qo` frequently to see which package provides an executable. Then let's say I'm on a fedora:32 system, I'll end up doing something like this:

```console
$ pacman -Qo adduser
error: file /adduser: No such file or directory
$ which adduser
bash: which: command not found
$ type adduser
adduser is /usr/sbin/adduser
$ pacman -Qo /usr/sbin/adduser
shadow-utils-4.8.1-2.fc32.x86_64
```

**Comment by AndydeCleyre** [comment]
Ah, but a detail: if `which` is (also) provided by the shell (as in ZSH), then `type` will report that it's a builtin, while `whereis` will report the package-provided path, as will real `pacman -Qo`.

**Comment by icy** [comment]
@AndydeCleyre 

> ```
> $ pacman -Qo adduser
> error: file /adduser: No such file or directory
> $ which adduser
> bash: which: command not found
> $ type adduser
> adduser is /usr/sbin/adduser
> $ pacman -Qo /usr/sbin/adduser
> shadow-utils-4.8.1-2.fc32.x86_64
> ```

What is the output of `rpm -qf adduser`? See also https://github.com/icy/pacapt/blob/0ef1133fc34a34a0099514106f4a9cb6019732fc/lib/yum.sh#L42

**Comment by AndydeCleyre** [comment]
> @AndydeCleyre
> What is the output of `rpm -qf adduser`?

```console
$ rpm -qf adduser
error: file /adduser: No such file or directory
```

This is within a container from the `fedora:32` image from docker hub.

**Comment by icy** [comment]
My so belated response, now with a PR: https://github.com/icy/pacapt/pull/152. Please have a look @AndydeCleyre and @cuonglm . Thanks.
