### ISSUE TITLE
apt-cyg support?

### ISSUE THREAD

**Issue by AeriaVelocity** [icy/pacapt#206]
Could support for Cygwin's `apt-cyg` be added?

**Comment by icy** [comment]
> Could support for Cygwin's `apt-cyg` be added?

Hi @That1M8Head, 

That's possible. The good news is that I have a Windows machine now (after years on Linux I need to buy a Windows node to get my midi controller to work :D).

Do you know any easy way to install Cygwin? The last time I did that was kind 12 years ago [1]. That would save me a bit of time.

Thanks

[1] https://github.com/viettug/vnmik4

**Comment by AeriaVelocity** [comment]
Cygwin isn't too hard to install, it has a guided installer which you can also install packages with. `apt-cyg` is available from [here](https://github.com/transcode-open/apt-cyg). Everything you need should be in that repo.

**Comment by AeriaVelocity** [comment]
How's that going?

**Comment by icy** [comment]
Hi @That1M8Head , sorry for the belated response. We will have an initial support early next week. Stay tuned!

**Comment by icy** [comment]
@That1M8Head , we've had a new releases v3.0.5 (https://github.com/icy/pacapt/releases/tag/v3.0.5) with the initial support for cygwin/apt-cyg. The backend has some nice features that I want to add, but tbh, my time is suddenly limited these days. Some tests are also failing but it's fine; I had all manual tests on cygwin (search, add, remove, update package databases or so). 

Please give them a try and let me know if you would see any issues / ideas to improve the tool. I also start to use the tool on my windows machine ;)

**Comment by AeriaVelocity** [comment]
Awesome! If I can help at all (y'know other than testing) then let me know!
