### ISSUE TITLE
How to uninstall???

### ISSUE THREAD

**Issue by ThatOneVideoGamer** [icy/pacapt#212]
So I just wanted to try this out but I cannot find anywhere on how to remove this now that I have it installed

**Comment by icy** [comment]
Hi @ThatOneVideoGamer ,

That depends on your installation method:

* If you downloaded and installed the script as seen in https://github.com/icy/pacapt#installation, you can simply remove the script from your system. To find where the script is, please type `command -v pacapt` (or `command -v pacaman` if you did rename the script before)
* If you installed the script via system package manager (i.e. `homebrew`), I would suggest you to follow their manual page to complete the uninstallation process.

Hope this helps.
