### ISSUE TITLE
Fix broken VM-based test setup

### ISSUE THREAD

**Issue by icy** [icy/pacapt#221]
pkgng and sunports both use VM-based test setup and they have been broken .

**Comment by mondeja** [comment]
Seems that `vboxmanage` is not included by Github in [macOS-11 machines](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md).

**Comment by icy** [comment]
> Seems that `vboxmanage` is not included by Github in [macOS-11 machines](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md).

No, it's not included there somehow. I will try to download the tool inside the VM. I saw the error (127 command not found) but I was expecting there was some upstream error :D
