### ISSUE TITLE
Hỗ trợ nhóm lệnh `yum group`

### ISSUE THREAD

**Issue by NgoHuy** [icy/pacapt#29]
Hiện tại trong `pacman` có option `-Sg` để liệt kê các gói trong một nhóm, thông tin nhóm, trong yum có lệnh tương ứng là `yum grouplist` và cài đặt nhóm `yum groupinstall` 

Đề xuất hỗ trợ cài đặt nhóm cho nhóm lệnh `yum`.

**Comment by icy** [comment]
Ok a sẽ coi xem. Cảm ơn @NgoHuy

**Comment by icy** [comment]
See also #30 . Pull request was rejected. Please consider to create another one. Thank you.
