### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by xiongchiamiov** [icy/pacapt#4]
Unfortunately, public domain is not well-defined; in fact, it's not even possible in some countries (Germany, iirc) to release things into the public domain.

Please consider changing the license to explicitly give away rights using [the WTFPL](http://sam.zoy.org/wtfpl/) or [the Fair License](http://www.opensource.org/licenses/Fair).

**Comment by icy** [comment]
Thank you _xiongchiamiov_. I will update license information soon.

**Comment by icy** [comment]
The WTFPL sounds fun :) Are there any problems if we use it for the tool? ("f*ck" may bother some people)

**Comment by xiongchiamiov** [comment]
Well, [there are some people](https://github.com/dimitri/el-get/issues/474) who get offended.  If that's of concern to you, I'd recommend using the Fair License - it's essentially the same thing.

I use the WTFPL for almost all of my personal projects, and it hasn't been an issue.  But then again, not many people use my stuff. ;)

**Comment by icy** [comment]
Thank you.

License information has been updated (https://github.com/icy/pacapt/commit/8975fb237bb5f3737a85bb08a91cb960fbcd839e).

Please let me know if there is any problem.
