### ISSUE TITLE
Add "assumeyes" or "noconfirm" option

### ISSUE THREAD

**Issue by rndmh3ro** [icy/pacapt#43]
Right now there's no way to perform an unattended installation of a package, e.g.

```
/usr/bin/pacman -S foo --noconfirm
```

or

```
yum install foo --yes
```

There should be something like

```
pacacpt -S foo --yes
```

**Comment by icy** [comment]
Nice idea, @rndmh3ro . I will wok on this.

**Comment by ssbarnea** [comment]
:+1: wondering why is closed, not having this is a deal breaker for me.

**Comment by icy** [comment]
@ssbarnea The remote ticket (https://github.com/hardening-io/tests-ssh-hardening/issues/47) is closed (actually it's escalated to _ansible-kitchen_ project).

This ticket per-se is still open, and I hope to get it done in the next release. Stay tuned!

**Comment by NgoHuy** [comment]
please check my pull request #49 
Thank you very much

**Comment by rndmh3ro** [comment]
In PR #49 @NgoHuy added some commits to make "noconfirm" happen. Were you able to merge these commits, @icy?

**Comment by icy** [comment]
Hi @rndmh3ro. I will take a look when I'm back from holiday. Possibly next week. Thanks a lot.

**Comment by icy** [comment]
@NgoHuy Please check the latest commit (https://github.com/icy/pacapt/commit/8654c26d0cf90fa9894bb2c2905e3567be3d3771). 

All you need is to support more translations to the `_translate_noconfirm` method (See https://github.com/icy/pacapt/blob/ng/lib/00_core.sh#L152) . 

Thanks

**Comment by icy** [comment]
Now supported in `Debian`, CentOS/Fedora, Zypper and FreeBSD

**Comment by rndmh3ro** [comment]
Thank you!

**Comment by NgoHuy** [comment]
I see, thank you
