### ISSUE TITLE
homebrew: is $(brew --cache) safe?

### ISSUE THREAD

**Issue by icy** [icy/pacapt#47]
CC @xiongchiamiov 

Link to source code: https://github.com/icy/pacapt/blob/ng/lib/homebrew.sh#L109

The (`homebrew_Sccc`) function will delete all files from `$(brew --cache)`. Is that expansion safe, @xiongchiamiov ?

I have disabled the feature (`homebrew/Sccc`), but we can enable them quickly after a confirmation.

**Comment by xiongchiamiov** [comment]
I can't find an online copy of it, but it's actually the recommendation of the homebrew man page:

> cleanup [--force] [--prune=<days>] [-ns] [formulae]
>     If  -s  is passed, scrubs the cache, removing downloads for even the latest versions of formula. Note downloads for any installed formula will still
>               not be deleted. If you want to delete those too: rm -rf $(brew --cache)

**Comment by xiongchiamiov** [comment]
Although to be safe, I suppose it should be quoted (`rm -rf "$(brew --cache)"`) in case someone sets it to a directory with a space in it.  But I don't even know if you can do that without modifying the homebrew source, and it'd be a stupid thing to do.

**Comment by icy** [comment]
Thank you for your information, @xiongchiamiov .

What is the result of `brew --cache`? Is that a path or a set of paths?

**Comment by xiongchiamiov** [comment]
It's a single path, generally `/Library/Caches/Homebrew` or `~/Library/Caches/Homebrew`.  I believe it should always be a single directory.

**Comment by icy** [comment]
Thank you @xiongchiamiov . I have committed in https://github.com/icy/pacapt/commit/b369d7edbc3b4050004ec0d1c4ca80faade0acba
