### ISSUE TITLE
Support -Sii

### ISSUE THREAD

**Issue by xiongchiamiov** [icy/pacapt#50]
Today I found myself wondering why I had a certain package installed, and discovered that pacman's `-Sii` operation (find reverse dependencies) isn't yet implemented.

It [looks like](https://wiki.archlinux.org/index.php/Pacman_Rosetta) it's not incredibly widely-supported, but it'd be nice to have for the systems that have that information.

**Comment by NgoHuy** [comment]
I see it same as `-Qi` , should we implement it ?

**Comment by icy** [comment]
It's not the same, Huy.

**Comment by NgoHuy** [comment]
my fault :)

**Comment by icy** [comment]
`Sii` is now supported in `dpkg` and `yum`.

**Comment by xiongchiamiov** [comment]
You're a boss. :)

**Comment by icy** [comment]
Now we have a fancy table to see if something is missing: https://github.com/icy/pacapt#implemented-operations ;)
