### ISSUE TITLE
[Request] pacman -Ss

### ISSUE THREAD

**Issue by baronleonardo** [icy/pacapt#53]
Could you make the output of this command `pacman -Ss` in Ubuntu/Debian looks like the output of the same command in Arch ?

**Comment by NgoHuy** [comment]
It denpends on apt-cache's format, we should keep this.

**Comment by icy** [comment]
@baronleonardo Do you have any special reason for that? That would be possible with help of an output parser, but we need strong reason to move on.

**Comment by icy** [comment]
@baronleonardo You can simply do this

```
pacman -sS foo | awk -F " - " '{printf("%s\n    %s\n", $1, $2);}
```

This doesn't include status of a package (installed or not) though. On ArchLinux, a search command (-sS) will let you know whether a package is installed.

**Comment by baronleonardo** [comment]
I find it more useful to preview it as Arch
package + current version + small description + installed or not
it is very useful actually

@icy Thanks for your help. 
I appreciate that.
But I was looking for something like what I have said above.

**Comment by icy** [comment]
@baronleonardo I agree. I will take a look if there is a way to support this kind of output filter.

**Comment by NgoHuy** [comment]
You can patch my script as below, only installed packages will have version :)

``` #!/bin/bash
IFS=$'\n' packages=($(apt-cache search "$1"))
for package in ${packages[@]}
do
  name=${package%% - *}
  desc=${package#* - }
  dpkg-query -W "$name" > /dev/null 2>&1
  if [[ $? -eq 1 ]]; then
    echo -e "package/$name \n    $desc"
  else
    dpkg-query -W -f='package/${binary:Package} ${Version}\t[${Status}]\n    ${binary:Summary}\n' "$name"
  fi
done
```

**Comment by icy** [comment]
@NgoHuy Can you please submit a patch? Thanks

**Comment by icy** [comment]
Fixed in https://github.com/icy/pacapt/pull/156 . Thanks @cuonglm and @NgoHuy for your great support.
