### ISSUE TITLE
Must we  create an enforcement for quoting variable?

### ISSUE THREAD

**Issue by cuonglm** [icy/pacapt#54]
As previous describing in [this issue](https://github.com/icy/pacapt/issues/40), forgetting to quote variables in shell script leading to many security implications.

Example in `compile.sh` line `95` -> `99`:

```
for L in ./lib/*.sh; do
  [[ "${L##*/}" != "zz_main.sh" ]] \
  || continue

  $GREP -v '^#' $L
done
```

this can be easily fooled by creating a file `* *.sh` in `./lib`, causing the content of all lib files printed twice. It's just a simple case, there can be many hidden weird behaviors that we can not cover, like code injection.

Is it time to make an enforcement for contributors to quote all the variables?

**Comment by icy** [comment]
Hi @Gnouc ,

I'm sorry for my belated reponse. 

Thank you for the great catch. I don't know there is any automatic tool to enforce this. In the mean time, it would be part of the coding style (I will emphasize in https://github.com/icy/bash-coding-style).

The `compile.sh` is used once by our developer. I will review all changes if there is any similar issue at run-time.

Thanks again.

**Comment by cuonglm** [comment]
@icy: We can use [shellcheck](http://www.shellcheck.net/) to make a checking before pull request, every pull without passing shellcheck will be denied.

About my example. It's more about internal usage by our developer. In the real world, everyone on system which hold `pacapt` source code and have the write access to the `pacapt` source directory can be do that trick.

I shown the example only for pointing out a possible case. There can be others that we can not coverage.

And actually, it can make `pacapt` run a litter faster because don't quote variable actually called `split+glob` operator.

**Comment by icy** [comment]
Excellent. Thanks for sharing. I will take a look whether we can use `shellcheck` .

**Comment by NgoHuy** [comment]
simply, I define an array `LIST=(dpkg yum ....)` and check in this, does it avoid problem ?

**Comment by cuonglm** [comment]
@NgoHuy: It's only a workaround, and require you to change your code structure.

Generally, if you don't want to use `shellcheck`, or you have trouble with typing many double quotes, you have to:
- Setting `IFS` to consistent value
- Using `set -f` to disable globbing and `set +f` to enable when you need it

But I think it will lead to more works than simply always double quotes variables.

**Comment by NgoHuy** [comment]
in this scripts, "$_TOPT" will make it fail if value includes space, etc... bash's easy to use but more risk haha

**Comment by xiongchiamiov** [comment]
http://mywiki.wooledge.org/Quotes is an excellent document detailing best practices for quoting (see also [the Bash Pitfalls page](http://mywiki.wooledge.org/BashPitfalls), where many issues are related to quoting).

**Comment by icy** [comment]
@xiongchiamiov Thanks for the link. It's always fun to run `Wooledge`. I often read from http://wiki.bash-hackers.org/, and most of the time I try to look up something releated to shell expansions ;)

@Gnouc I have some time to try `shellcheck`. I use the online version of the tool to check against the latest stable version (v2.1.6). The most useful suggestion is to exit after a `cd` command in `homebew_Qo` method.

Regarding the quoting support for a `for` statement as you mentioned in the first comment, I will try some way. Because `for L in "./lib/*.sh"; do [...]; done` just fails the script.

**Comment by cuonglm** [comment]
@icy Yep, you can't do globbing inside double quotes.

`for L in ./lib/*.sh` is fine, just using `$L` with double quotes.

**Comment by icy** [comment]
Ah, my bad. Would fix that very soon. Thanks again.

**Comment by icy** [comment]
Please see the `make shellcheck` and the latest script `bin/check.sh`. The script will send request to http://www.shellcheck.net/ to check all scripts.

Not sure this is against any terms of use of the site. ping @koalaman (https://github.com/koalaman)

**Comment by icy** [comment]
Output excerpt

```
$ make shellcheck
:: Checking bin/check.sh...
:: Checking bin/compile.sh...
  style 2002: line   56 col  0, msg Useless cat. Consider 'cmd < file | ..' or 'cmd file | ..' instead.
   info 2162: line  120 col  0, msg read without -r will mangle backslashes.
   info 2016: line  126 col  0, msg Expressions don't expand in single quotes, use double quotes for that.
:: Checking lib/00_core.sh...
  error 2145: line   15 col  0, msg Argument mixes string and array. Use * or separate argument.
warning 2153: line   25 col  0, msg Possible misspelling: _POPT may not be assigned, but _TOPT is.
warning 2153: line   25 col  0, msg Possible misspelling: _SOPT may not be assigned, but _TOPT is.
   info 2016: line  143 col  0, msg Expressions don't expand in single quotes, use double quotes for that.
   info 2162: line  145 col  0, msg read without -r will mangle backslashes.
:: Checking lib/cave.sh...
   info 2162: line   40 col  0, msg read without -r will mangle backslashes.
   info 2162: line   61 col  0, msg read without -r will mangle backslashes.
   info 2086: line  144 col  0, msg Double quote to prevent globbing and word splitting.
   info 2086: line  147 col  0, msg Double quote to prevent globbing and word splitting.
:: Checking lib/dnf.sh...
   info 2086: line    4 col  0, msg Double quote to prevent globbing and word splitting.
:: Checking lib/dpkg.sh...
   info 2162: line   44 col  0, msg read without -r will mangle backslashes.
   info 2162: line   49 col  0, msg read without -r will mangle backslashes.
  error 2145: line   69 col  0, msg Argument mixes string and array. Use * or separate argument.
   info 2086: line  130 col  0, msg Double quote to prevent globbing and word splitting.
```

**Comment by icy** [comment]
(See `col 0` as there is a problem with the script, has been fixed in the latest commit.)

**Comment by icy** [comment]
And with colorful output http://www.enlightenment.org/ss/e-55c35bc43d6938.66018597.jpg

**Comment by koalaman** [comment]
@icy I certainly don't mind, I'm glad you find it useful! There are no specific terms, but also no guarantees :P 

PS: if you want to enable offline checking, `shellcheck -f json filename` is a drop-in replacement for the web service

**Comment by icy** [comment]
> @icy I certainly don't mind, I'm glad you find it useful! There are no specific terms, but also no guarantees :P

Thanks a lot :) Your tool is very beautiful !

> PS: if you want to enable offline checking, `shellcheck -f json filename` is a drop-in replacement for the web service

I have sent a pull request (https://github.com/koalaman/shellcheck/pull/426) that explains why I like the web service ;)

**Comment by icy** [comment]
I close this ticket because we have a tool to check our scripts now :)
