### ISSUE TITLE
opkg support

### ISSUE THREAD

**Issue by urandom2** [icy/pacapt#62]
It would be awesome if you could add support for [opkg](https://en.wikipedia.org/wiki/Opkg).

**Comment by icy** [comment]
Hi @arnottcr,

I will take a look .

**Comment by icy** [comment]
Porting `pacapt` to support `opkg` is a real challenge. In  `OpenWRT` embeded environment, `(d)ash` is used instead of `bash`; and other standard tools are implemented in a different fashion (Not related, but it's true that `wget` in `OpenWRT` doesn't support `https`.)

CC: @cmpitg and @Gnouc if you have any brilliant ideas.

**Comment by urandom2** [comment]
While I agree it would add complexity, you could have a vanilla POSIX header that determines the shell and then code paths for each major subgroup. I would imagine that this within the realm of what I am capable of, so if I get time I may submit a pull request, or be back with comments/questions.

Also, from what I have seen bash is great for interactivity, but not the fastest at executing POSIX scripts, so there could be merit in migrating to a pure POSIX implementation of pacapt.

(I agree it is odd that wget does not support tls, then again most package managers I have worked with, pacman included, prefer http and signatures over https.)

**Comment by cuonglm** [comment]
@arnottcr pacapt code base relied heavily on non-POSIX shell features, example process substitution, `local` variable, `globstar`. Not all of them can be made to work in POSIX shell.

It need a big effort to porting it to a POSIX implementation.

**Comment by urandom2** [comment]
@Gnouc, thanks; I have not looked in depth at the pacapt codebase, but that seems quite reasonable. [sarcasm] I will submit a pull request when I have all the porting done. [/sarcasm]

**Comment by icy** [comment]
I think it's good to start new branch, e.g, `paccapt_posix`. I also need some testing support. (For now, all tests are done manually.) There are many things to do now :D

**Comment by icy** [comment]
@arnottcr  @Gnouc 

`pacapt` main part is now written in `Dlang`. WIP found from `nd` branch https://github.com/icy/pacapt/tree/nd. 

I will take a look how the application can be built on ` OpenWRT`. After that we can start new support for `opkg`.

**Comment by icy** [comment]
@arnottcr  `POSIX` environment now can be supported thanks to #161 . Once it's merged I'll get back to this issue. Thanks.

**Comment by icy** [comment]
Due to wrong linking the ticket was closed automatically. I reopen it now. Thanks.

**Comment by icy** [comment]
A quite complete `opkg` support : https://github.com/icy/pacapt/pull/162/files#diff-88f1c7341e39e99c75f394dc9cccbebdc080299d915d4839bfb85352740d9385

Please help to review PR and I'll release them next week. Thanks.

**Comment by icy** [comment]
I'm happy to release new version `v3.0.0`, its `opkg` support is ready :) I would have written the script with `POSIX` from the first day (kinda 11 years ago:D). This request is > 5 years ago, but it's still better to have something late than... never.

Enjoy `opkg` support: https://github.com/icy/pacapt/releases/tag/v3.0.0

edit: fix typ0
