### ISSUE TITLE
Support pacman -Rsc

### ISSUE THREAD

**Issue by ThePreviousOne** [icy/pacapt#71]
I don't know how common this is but I use it alot (I ran Antergos for A short while(lots of garbage from install)) and I could make great use of _Remove- package, dependacies, and dependants_ after new debian of Ubuntu installs

**Comment by icy** [comment]
@NgoHuy Please take a look. Thanks

**Comment by NgoHuy** [comment]
Because `-c` option is dangerous 

```
Remove all target packages, as well as all packages that depend on one or more target packages. This operation is recursive and must be used with care, since it can remove many potentially needed packages.
```

I'm checking some safe way to remove `dependants` without breaking system as this behaviour

**Comment by NgoHuy** [comment]
In the scenario, A depends on B, we remove B, A will be removed, C depends on A, but C is explicit packages installed before... How do we handle this case ?
I don't support this case now :)

**Comment by evenreven** [comment]
This sounds dangerous to me too, but I'm no pacman expert. What's the benefit of using `-c` over `pacman -Rns $(pacman -Qtdq)`? That's my autoremove alias (which I stole [from the Arch Wiki](https://wiki.archlinux.org/index.php/Pacman/Tips_and_tricks#Removing_unused_packages_.28orphans.29)).

**Comment by NgoHuy** [comment]
@evenreven it's good, it removes all packages which are not required by any packages ( orphan packages), but the mean is not same as `-c` and we will implement `-Qtd` too :dancer:

**Comment by evenreven** [comment]
Cool. Yeah, thanks, I see the difference now.

**Comment by icy** [comment]
@NgoHuy Can you please have some demo , e.g., the output of these commands? Thanks

**Comment by NgoHuy** [comment]
@icy see below
first:

```
$ sudo pacman -Rns pacman       
checking dependencies...
error: failed to prepare transaction (could not satisfy dependencies)
:: package-query: removing pacman breaks dependency 'pacman>=5.0'
:: pkgfile: removing pacman breaks dependency 'pacman'
:: yaourt: removing pacman breaks dependency 'pacman>=5.0'
```

second:

```
$ sudo pacman -Rsc pacman
checking dependencies...
warning: pacman is designated as a HoldPkg.
:: HoldPkg was found in target list. Do you want to continue? [y/N] y

Packages (5) archlinux-keyring-20160215-1  package-query-1.8-2  pkgfile-15-1  yaourt-1.8.1-1  pacman-5.0.1-2

Total Removed Size:  5.81 MiB
```

The second will remove archlinux-keyring too

**Comment by icy** [comment]
Perfect @NgoHuy  . A picture always makes a thousand words ;)

**Comment by icy** [comment]
But, how about `acman -Rns $(pacman -Qtdq)`? That's too magic to me =))

**Comment by NgoHuy** [comment]
you can see `pacman -Qi somepackage` : 
Install Reason field  : `Installed as a dependency for another package` but `required by is none.`

`pacman -R somepakage_same_above && pacman -S sompackage_same_above`
Install Reseason field: `Explicitly installed`

**Comment by NgoHuy** [comment]
`-Qdt` show only dependecies are not required by any package :)

**Comment by icy** [comment]
Thanks again, @NgoHuy . I just want to make sure future reader (of this topic) can fully understand you hehe

**Comment by NgoHuy** [comment]
you're welcome :)

**Comment by ThePreviousOne** [comment]
So that's a no to -c then?

**Comment by NgoHuy** [comment]
for confirmation, yes.
