### ISSUE TITLE
Fedora 22/23 uses dnf

### ISSUE THREAD

**Issue by Pival81** [icy/pacapt#75]
on fedora 23, when i enter `sudo pacapt -S texlive-bohr` it gives me this:
`Yum command has been deprecated, redirecting to '/usr/bin/dnf install texlive-bohr'.
See 'man dnf' and 'man yum2dnf' for more information.
To transfer transaction metadata from yum to DNF, run:
'dnf install python-dnf-plugins-extras-migrate && dnf-2 migrate'`

it still installs, but its a bit annoying.

**Comment by icy** [comment]
Thannks @Pival81 for your report.

@NgoHuy Can you please make `dnf` default on Fedora system?

**Comment by NgoHuy** [comment]
@icy : you did not update `pacapt` scripts in ng branch.
@Pival81 you should run `make pacapt.dev` and try again. I'm looking `pacapt` scripts has no detection for dnf now.

**Comment by icy** [comment]
Ah ok. The feature is on the latest development script but it's not in the latest stable script. I will update it today. Thanks.
