### ISSUE TITLE
To install packages i have to use sudo.

### ISSUE THREAD

**Issue by Pival81** [icy/pacapt#76]
When I try to install packages, at least on Fedora 23, it says that i have to be root to install them.
So i use sudo, but it gives me this error: 
`sudo: pacapt: command not found`
To solve this i linked `/usr/local/bin/pacapt` to `/bin/pacapt`, but it would be better if this was written in the install instructions.

**Comment by icy** [comment]
@Pival81 I will add notes to install instructions. Thank you very much!

**Comment by Pival81** [comment]
Also, i made an rpm package for pacapt, will upload it on the open build system.
I can also make a deb package.
If you're interested i can give you the link.

**Comment by icy** [comment]
hi @Pival81,

I focused on merging, and I forgot your last comment. I didn't intend to ignore your comment definitely!

Would you mind uploading the intructions to build packages (.rpm, .deb) in the `/contrib/` sub directory? I think it's useful for distribution maintainer. For the links to packages, I will provide them in the README file in case someone needs them.

I'm so sorry for my mistake and thanks a lot for your understanding!

**Comment by Pival81** [comment]
@icy hi, actually there is no need to give build instructions, as the precompiled rpms  and debs  are available here: http://software.opensuse.org/download.html?project=home:Pival81&package=pacapt
But anyway, how should i upload the instructions? i don't see a contrib directory in the code.

**Comment by icy** [comment]
Thanks a lot, @Pival81 . Please create the first files for that directory :)

**Comment by icy** [comment]
See also #80.
