### ISSUE TITLE
Yaourt search packages 

### ISSUE THREAD

**Issue by Pival81** [icy/pacapt#77]
I remember when i used arch, that if i wanted to search and install a package, i typed `yaourt <package>`, and it listed all the packages with a number, and it asked me the number of the package(s) i wanted to   install.
It would be awesome to have this in pacapt.

**Comment by TomaszGasior** [comment]
In my opinion it's not good idea. Pacapt is only wrapper for package managers such as dpkg. It should not contain other features.

**Comment by anna328p** [comment]
-1 Use `-Ss`. yaourt is bad.
