### ISSUE TITLE
Open a Gitter room.

### ISSUE THREAD

**Issue by Pival81** [icy/pacapt#82]
It would be easier for the contributors to say something without having to create new issues for simple stupid things.
For example, you forgot to create a new release for 2.3.11, so the spec file in `contrib` won't work anymore, as it downloads from the releases.
EDIT: oh, ok, you created it. still we need gitter.

**Comment by icy** [comment]
Hi @Pival81,

I haven't used Gitter because I'm on Telegram/IRC most of the time. Let me give it a try:)

**Comment by icy** [comment]
Thanks @Pival81  again. I have created new room here https://gitter.im/icy/pacapt.
