### ISSUE TITLE
Installed packages are incorrect (Debian) 

### ISSUE THREAD

**Issue by ceribik** [icy/pacapt#84]
As per title. I'm running Debian Jessie.

> $ pacapt -Qs mysql
> libaprutil1-dbd-mysql
> libdbd-mysql
> libdbd-mysql-perl
> libmysqlclient18:i386
> mysql-client-5.1
> mysql-common
> mysql-server-5.1
> mysql-server-core-5.1
> rsyslog-mysql
> 
> $ pacapt -Qi mysql-server
> dpkg-query: package 'mysql-server' is not installed and no information is available
> Use dpkg --info (= dpkg-deb --info) to examine archive files,
> and dpkg --contents (= dpkg-deb --contents) to list their contents.
> 
> $ dpkg-query -l | grep mysql
> ii  libdbd-mysql-perl
> ii  libmysqlclient18:i386
> ii  mysql-common

**Comment by NgoHuy** [comment]
Hi Ceribik,
It's normal in debian as https://packages.debian.org/jessie/mysql-server

Vào Chủ Nhật, ngày 17 tháng 7 năm 2016, ceribik notifications@github.com
đã viết:

> As per title. I'm running Debian Jessie.
> 
> $ pacapt -Qs mysql
> libaprutil1-dbd-mysql
> libdbd-mysql
> libdbd-mysql-perl
> libmysqlclient18:i386
> mysql-client-5.1
> mysql-common
> mysql-server-5.1
> mysql-server-core-5.1
> rsyslog-mysql
> 
> $ pacapt -Qi mysql-server
> dpkg-query: package 'mysql-server' is not installed and no information is
> available
> Use dpkg --info (= dpkg-deb --info) to examine archive files,
> and dpkg --contents (= dpkg-deb --contents) to list their contents.
> 
> $ dpkg-query -l | grep mysql
> ii libdbd-mysql-perl
> ii libmysqlclient18:i386
> ii mysql-common
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
> https://ci5.googleusercontent.com/proxy/OijihtiXV1UG_C6tEJi0jcrbp2GLI-ySmrVOMqOO7RYB1rXgFy1WfIq3NwVCGC_U37fRYIQuNhXcnUf2IHiSXCL5VXx79t-DDUU1QjTsDLNTZ2y5nkFMQ5iUQ3Li-bF9jOJJobaPC6-9ipiB2r3pAXF8rxqglw=s0-d-e1-ft#https://github.com/notifications/beacon/ABLkYKDWelcXqAmVRLiraKIxPWD8ZP9Qks5qWYtHgaJpZM4JOIjx.gif

## 

Be different and always different

**Comment by icy** [comment]
Hi @ceribik,

Thanks for your report. `-Qs` should

**Comment by icy** [comment]
hi @ceribik ,

I have attempted to fix in the latest commit, however the behavior is a bit different between Arch and Debian (See also in the commit comments)

Please let me know if that's expected / acceptable.

Thanks a lot.

**Comment by icy** [comment]
btw, the latest commit is on the development branch, and it's required you to compile the script manually (`make pacapt.dev`). So I add here some screenshots

```
$ pacapt.dev -Qs bash
bash                                  4.3-7ubuntu1.5                          amd64        GNU Bourne Again SHell

$ pacapt.dev -Qs bash*
bash                                  4.3-7ubuntu1.5                          amd64        GNU Bourne Again SHell
bash-completion                       1:2.1-4                                 all          programmable completion for the bash shell
```

**Comment by ceribik** [comment]
@NgoHuy In Arch, pacman -Qs always searches for locally installed packages and nothing else, and so I just assumed that pacapt would too. If i wanted to search for remote packages, I would use -Ss ala pacman.

@icy I tried your patch and that seemed to fix the issue, although as you noted, the search pattern now seems to be different from arch in that searching for "mysql" won't find "mysql-common", where as it would in Arch. 

What's the rationale behind requiring the \* glob for searching?

current/patch: 

> dpkg-query -l "${@}" \

more arch-like?:

> dpkg-query -l "${@}*" \

**Comment by icy** [comment]
@ceribik It's because of the difference in regex syntax. I'm not sure if adding a star (`*`) would help. I will be back to this later. Thanks.

**Comment by icy** [comment]
Hi @ceribik,

I've fixed in the latest commit. The idea is to use `grep` to filter the output of `dpkg-query` command, and by this way we don't have to worry about distribution specification.

Thanks,

**Comment by ceribik** [comment]
Looks good, thanks @icy

**Comment by icy** [comment]
You're welcome:)

**Comment by icy** [comment]
And thank you very much for your bug reporting :)
