### ISSUE TITLE
Around pacapt

### ISSUE THREAD

**Issue by Grenadingue** [icy/pacapt#89]
Hi guys,

I wanted to tell you that I like what you did with `pacapt` ! I often use it on non-Arch distributions, for my personal usage.

I found `pacapt` so useful that I decided to use it, as a part of a school projet, a quite big projet. It's named [`SAM-Solution`](https://github.com/EIP-SAM), it intends to be a system administrator solution for managing a Linux/Windows computers park. You can find more details about the project [here (main repo)](https://github.com/EIP-SAM/SAM-Solution-Server), and [here (showcase website)](https://eip-sam.github.io).

So, for the needs of `SAM-Solution` I first wrapped `pacapt` in an `npm` package, to be able to use it with `node.js`, and to easily make queries and retrieve the output from it. Here is the repo [`node-pacapt`](https://github.com/Grenadingue/node-pacapt).

I also made a `pacapt` adaptation for Windows, written in `batch`, wrapping the well known [`chocolatey`](https://github.com/chocolatey/choco). Here is the repo [`batch-pacapt`](https://github.com/Grenadingue/batch-pacapt).

All of these repositories are still under development stage, but I wanted to share it with you because they are strongly linked with this one.

I'm interested and open to any kind of linking/merging of the various `pacapt` repositories. Let's discuss it if you're interested too.

Cheers !

**Comment by icy** [comment]
Hello, @Grenadingue, 

I'm happy that the script is useful in your project.  And thank you for your works they're very interesting.

Give me some days I will take a look at them and see whether I can help a/o we can work together.

Cheers,

**Comment by icy** [comment]
Hi @GijsTimmers,

I have changed to work with some `nodejs` projects, that allows me to have a better chance to promote your project. I have added links also (https://github.com/icy/pacapt#related-projects).

Thanks again and i'm very sorry for the delay.
