### ISSUE TITLE
No Confirm

### ISSUE THREAD

**Issue by p1839251** [icy/pacapt#91]
Alright, this is a feature request. <If I had known how to add labels to this, I would've done that.>

I personally often times install programs or update my system with the flag --noconfirm.
I know it's not really recommended, however, if I want to install a specific application, I will do it any way.
It's kind of time saving. After running pacapt -Syu or just pacapt -S 'anything', it loads for a while and then asks the question. I could leave the room right after typing the root passwd or I could use pacapt in scripts.
e.g.
sudo pacapt -Syu --noconfirm or sudo pacapt -S nano --noconfirm

I've just looked after it, apt-get supports this: --assume-yes or --force-yes, as does zypper --non-interactive . I haven't tried them, though. I'm quite sure all the other package manager supports this somehow.

Besides this pacapt works really well. I love it. I don't need to memorize lots of other commands.
Keep up the good work!

**Comment by NgoHuy** [comment]
Hi,
We have implemented this feature
`pacapt -Syu --noconfirm` or `pacapt -S --noconfirm fish` this feature only supports as below
![090405170946](https://cloud.githubusercontent.com/assets/1238112/25689073/ac3abf0a-30ae-11e7-8465-c02703f01146.jpg)

**Comment by p1839251** [comment]
Hello,
Thank you for your reply.
Yep I used to enter it the other way around. pacapt -S app --noconfirm.

So I wish to change this request into a bug report then.
As it seems --non-interactive wasn't a good hint.
![screen](https://cloud.githubusercontent.com/assets/27902026/25693387/4e3815c4-30a9-11e7-8fac-c2329564571a.png)

(pacman is pacapt, I just prefer to use it that way)

I tried using --noconfirm on *Ubuntu, and worked flawlessly.

**Comment by NgoHuy** [comment]
Thank @p1839251 
I can reproduce your problem. I see this should be `zypper --non-interactive [options]` NOT `zypper [options] --non-interative`

**Comment by NgoHuy** [comment]
I just made pull request https://github.com/icy/pacapt/pull/92. Can you check it ?

**Comment by p1839251** [comment]
Confirmed
With --no-confirm (instead of  --non-interactive), I am able to update the system, install or even remove applications.
Thank you for your contribution!

**Comment by icy** [comment]
Thanks a lot for your reporting @p1839251 . I will prepare a new release soon.
