### ISSUE TITLE
Support -q flag for quiet

### ISSUE THREAD

**Issue by ghost** [icy/pacapt#96]
Is this something that you're ever planning to do? Honestly, this would make this a lot more usable for me, because it'd let me do things like `pacapt -R $(pacapt -Qsq blahstuff)` which is a lot more intuitive than having to parse the output further. I know it'd require a bit of text manipulation, and that's not Bash's strong suite. (I'm honestly not sure why people write such large projects in Bash :P )

If this is something you plan to do, maybe you should add it to the automatically generated table. I _really_ hope it is, as it'd make things a ton easier. You accept pull requests? You're probably a lot better at me at coding in Bash than I am, but I could give implementing this a try if no one else wants to.

**Comment by icy** [comment]
Hi @avrildev,

Thanks for your feedback. There is `-q` option but it doesn't work consistently: `pacman -Qq` works, but `pacman -Qqs` doesn't. I will take a look.  I hadn't known there is `pacman -Qqs` operation until I read this post. My bad 🗡 

What distro are you working on? 

A lot of text processing can be done with `bash`, `awk`, `sed`, `grep`,... For complex things (as you see here https://github.com/icy/pacapt/blob/ng/bin/gen_tests.rb) I agree that `bash` is not enough. The truth is that I haven't seen any real problem with non-bash things in `lib/*` so far -- that's the source of `pacapt` power ;)

**Comment by ghost** [comment]
Most of my machines run stock Arch currently, but I use Ubuntu 16.04 for business-grade systems, and my Raspberry Pis run Raspbian. (Although I think Arch ARM could be entertaining to try out!)

Last time I tested pacapt, I had a Linux Mint 18.1 Serena install, which is of course basically Ubuntu. If it's testing you want, I'd be very happy to install a Debian/Ubuntu chroot/VM for testing. Or Fedora/CentOS for yum, but I can't promise I'll be able to debug very intelligently on those. :P 

Also, I, ahem, don't currently know Ruby fluently. I've been working on learning it, but I wouldn't want to waste your time with pull requests for sloppy code. I actually didn't notice this project incorporated Ruby, but I can definitely see why you'd choose it. I've read that it's nearly as fast as Bash. And it's definitely much more readable, for me anyway!

Edit: Also should mention, there's a `-Ssq` operation too! It does pretty much what you'd expect. The `-q` modifier applies to anything that lists stuff, AFAIK.

**Comment by icy** [comment]
@ghost Sorry for the belated feedback. Should be fixed with https://github.com/icy/pacapt/issues/143. I'm closing this issue and sending new Pr.
